class BibliographyItem {
  final int id;
  final String titleAr;
  final String titleEn;
  final String authorAr;
  final String authorEn;
  final String deathYear;
  final String category;
  final String categoryAr;
  final String description;

  const BibliographyItem({
    required this.id,
    required this.titleAr,
    required this.titleEn,
    required this.authorAr,
    required this.authorEn,
    required this.deathYear,
    required this.category,
    required this.categoryAr,
    required this.description,
  });
}

class BibliographyData {
  static const List<BibliographyItem> items = [
    // I. Primary Canonical Hadith Collections (أمهات كتب الحديث والمسانيد)
    BibliographyItem(
      id: 1,
      titleAr: 'صحيح البخاري (الجامع المسند الصحيح المختصر)',
      titleEn: 'Sahih al-Bukhari',
      authorAr: 'الإمام محمد بن إسماعيل البخاري',
      authorEn: 'Imam Muhammad ibn Isma\'il al-Bukhari',
      deathYear: '256 هـ',
      category: 'Canonical Collections & Musnads',
      categoryAr: 'أمهات كتب الحديث والمسانيد',
      description: 'The most authentic book after the Noble Qur\'an, foundational source for theological and legal rulings.',
    ),
    BibliographyItem(
      id: 2,
      titleAr: 'صحيح مسلم (المسند الصحيح المختصر بنقل العدل عن العدل)',
      titleEn: 'Sahih Muslim',
      authorAr: 'الإمام مسلم بن الحجاج النيسابوري',
      authorEn: 'Imam Muslim ibn al-Hajjaj an-Naysaburi',
      deathYear: '261 هـ',
      category: 'Canonical Collections & Musnads',
      categoryAr: 'أمهات كتب الحديث والمسانيد',
      description: 'Renowned for rigorous thematic arrangement and uninterrupted chains of transmission.',
    ),
    BibliographyItem(
      id: 3,
      titleAr: 'سنن أبي داود',
      titleEn: 'Sunan Abi Dawud',
      authorAr: 'الإمام أبو داود سليمان بن الأشعث السجستاني',
      authorEn: 'Imam Abu Dawud Sulayman ibn al-Ash\'ath',
      deathYear: '275 هـ',
      category: 'Canonical Collections & Musnads',
      categoryAr: 'أمهات كتب الحديث والمسانيد',
      description: 'The premier reference work for legal traditions (Ahadith al-Ahkam) governing daily life.',
    ),
    BibliographyItem(
      id: 4,
      titleAr: 'جامع الترمذي (السنن)',
      titleEn: 'Jami\' at-Tirmidhi',
      authorAr: 'الإمام أبو عيسى محمد بن عيسى الترمذي',
      authorEn: 'Imam Abu \'Isa Muhammad ibn \'Isa at-Tirmidhi',
      deathYear: '279 هـ',
      category: 'Canonical Collections & Musnads',
      categoryAr: 'أمهات كتب الحديث والمسانيد',
      description: 'Celebrated for explicit hadith gradings, comparative jurisprudence, and juristic consensus.',
    ),
    BibliographyItem(
      id: 5,
      titleAr: 'سنن النسائي (المجتبى والسنن الكبرى)',
      titleEn: 'Sunan an-Nasa\'i (Al-Mujtaba)',
      authorAr: 'الإمام أبو عبد الرحمن أحمد بن شعيب النسائي',
      authorEn: 'Imam Ahmad ibn Shu\'ayb an-Nasa\'i',
      deathYear: '303 هـ',
      category: 'Canonical Collections & Musnads',
      categoryAr: 'أمهات كتب الحديث والمسانيد',
      description: 'Highest critical narrator standards among the Sunan collections, with minute defect analysis.',
    ),
    BibliographyItem(
      id: 6,
      titleAr: 'سنن ابن ماجه',
      titleEn: 'Sunan Ibn Majah',
      authorAr: 'الإمام أبو عبد الله محمد بن يزيد بن ماجه القزويني',
      authorEn: 'Imam Muhammad ibn Yazid ibn Majah',
      deathYear: '273 هـ',
      category: 'Canonical Collections & Musnads',
      categoryAr: 'أمهات كتب الحديث والمسانيد',
      description: 'One of the six canonical books (Kutub al-Sittah), known for concise chapters and rich legal content.',
    ),
    BibliographyItem(
      id: 7,
      titleAr: 'موطأ الإمام مالك',
      titleEn: 'Muwatta Malik',
      authorAr: 'إمام دار الهجرة مالك بن أنس الأصبحي',
      authorEn: 'Imam Malik ibn Anas al-Asbahi',
      deathYear: '179 هـ',
      category: 'Canonical Collections & Musnads',
      categoryAr: 'أمهات كتب الحديث والمسانيد',
      description: 'Earliest codified compendium combining authentic Sunnah with early legal practices of Madinah.',
    ),
    BibliographyItem(
      id: 8,
      titleAr: 'مسند الإمام أحمد بن حنبل',
      titleEn: 'Musnad Ahmad ibn Hanbal',
      authorAr: 'إمام أهل السنة أحمد بن محمد بن حنبل الشيباني',
      authorEn: 'Imam Ahmad ibn Muhammad ibn Hanbal',
      deathYear: '241 هـ',
      category: 'Canonical Collections & Musnads',
      categoryAr: 'أمهات كتب الحديث والمسانيد',
      description: 'The encyclopedic master treasury of authentic Prophetic narrations organized by Companions.',
    ),
    BibliographyItem(
      id: 9,
      titleAr: 'صحيح ابن خزيمة',
      titleEn: 'Sahih Ibn Khuzaymah',
      authorAr: 'الإمام أبو بكر محمد بن إسحاق بن خزيمة النيسابوري',
      authorEn: 'Imam Abu Bakr Muhammad ibn Ishaq ibn Khuzaymah',
      deathYear: '311 هـ',
      category: 'Canonical Collections & Musnads',
      categoryAr: 'أمهات كتب الحديث والمسانيد',
      description: 'Strict critical standard for sound transmission and legal jurisprudence.',
    ),
    BibliographyItem(
      id: 10,
      titleAr: 'صحيح ابن حبان (التقاسيم والأنواع)',
      titleEn: 'Sahih Ibn Hibban',
      authorAr: 'الإمام أبو حاتم محمد بن حبان البستي',
      authorEn: 'Imam Abu Hatim Muhammad ibn Hibban al-Busti',
      deathYear: '354 هـ',
      category: 'Canonical Collections & Musnads',
      categoryAr: 'أمهات كتب الحديث والمسانيد',
      description: 'Innovative thematic system analyzing commands, prohibitions, prophecies, and historical events.',
    ),
    BibliographyItem(
      id: 11,
      titleAr: 'المستدرك على الصحيحين',
      titleEn: 'Al-Mustadrak \'ala al-Sahihayn',
      authorAr: 'الحافظ أبو عبد الله الحاكم النيسابوري',
      authorEn: 'Imam al-Hakim an-Naysaburi',
      deathYear: '405 هـ',
      category: 'Canonical Collections & Musnads',
      categoryAr: 'أمهات كتب الحديث والمسانيد',
      description: 'Narrations meeting the criteria of Bukhari and Muslim with scholarly corrections by adh-Dhahabi.',
    ),
    BibliographyItem(
      id: 12,
      titleAr: 'السنن الكبرى والسنن الصغرى',
      titleEn: 'Al-Sunan al-Kubra & al-Sughra',
      authorAr: 'الحافظ أبو بكر أحمد بن الحسين البيهقي',
      authorEn: 'Imam Abu Bakr Ahmad ibn al-Husayn al-Bayhaqi',
      deathYear: '458 هـ',
      category: 'Canonical Collections & Musnads',
      categoryAr: 'أمهات كتب الحديث والمسانيد',
      description: 'Comprehensive legal documentation validating authentic Prophetic textual evidences.',
    ),
    BibliographyItem(
      id: 13,
      titleAr: 'سنن الدارقطني',
      titleEn: 'Sunan al-Daraqutni',
      authorAr: 'الإمام أبو الحسن علي بن عمر الدارقطني',
      authorEn: 'Imam Ali ibn Umar al-Daraqutni',
      deathYear: '385 هـ',
      category: 'Canonical Collections & Musnads',
      categoryAr: 'أمهات كتب الحديث والمسانيد',
      description: 'Crucial reference for critical narrators assessment, path divergences, and legal hadiths.',
    ),
    BibliographyItem(
      id: 14,
      titleAr: 'سنن الدارمي (المسند)',
      titleEn: 'Sunan al-Darimi',
      authorAr: 'الإمام أبو محمد عبد الله بن عبد الرحمن الدارمي',
      authorEn: 'Imam Abd Allah ibn Abd al-Rahman al-Darimi',
      deathYear: '255 هـ',
      category: 'Canonical Collections & Musnads',
      categoryAr: 'أمهات كتب الحديث والمسانيد',
      description: 'Exemplary introductory chapter on the superiority of Sunnah, knowledge, and memorization.',
    ),
    BibliographyItem(
      id: 15,
      titleAr: 'مصنف عبد الرزاق',
      titleEn: 'Musannaf Abd al-Razzaq',
      authorAr: 'الحافظ أبو بكر عبد الرزاق بن همام الصنعاني',
      authorEn: 'Hafiz Abd al-Razzaq as-San\'ani',
      deathYear: '211 هـ',
      category: 'Canonical Collections & Musnads',
      categoryAr: 'أمهات كتب الحديث والمسانيد',
      description: 'Monumental early 3rd-century collection recording Marfu traditions and Companion statements.',
    ),
    BibliographyItem(
      id: 16,
      titleAr: 'مصنف ابن أبي شيبة',
      titleEn: 'Musannaf Ibn Abi Shaybah',
      authorAr: 'الإمام أبو بكر عبد الله بن محمد بن أبي شيبة',
      authorEn: 'Imam Abu Bakr Abd Allah ibn Abi Shaybah',
      deathYear: '235 هـ',
      category: 'Canonical Collections & Musnads',
      categoryAr: 'أمهات كتب الحديث والمسانيد',
      description: 'Vast encyclopedia of hadiths, judicial verdicts, and historical reports from early generations.',
    ),
    BibliographyItem(
      id: 17,
      titleAr: 'مسند أبي يعلى الموصلي',
      titleEn: 'Musnad Abi Ya\'la al-Mawsili',
      authorAr: 'الحافظ أحمد بن علي بن المثنى التميمي',
      authorEn: 'Hafiz Ahmad ibn Ali al-Mawsili',
      deathYear: '307 هـ',
      category: 'Canonical Collections & Musnads',
      categoryAr: 'أمهات كتب الحديث والمسانيد',
      description: 'Renowned Musnad preserving precious early transmission routes and verified chains.',
    ),
    BibliographyItem(
      id: 18,
      titleAr: 'المعجم الكبير والمعجم الأوسط والمعجم الصغير',
      titleEn: 'Al-Mu\'jam al-Kabir, al-Awsat & al-Saghir',
      authorAr: 'الإمام أبو القاسم سليمان بن أحمد الطبراني',
      authorEn: 'Imam Sulayman ibn Ahmad at-Tabarani',
      deathYear: '360 هـ',
      category: 'Canonical Collections & Musnads',
      categoryAr: 'أمهات كتب الحديث والمسانيد',
      description: 'The tripartite dictionary collections compiling thousands of rare verified Companions\' reports.',
    ),
    BibliographyItem(
      id: 19,
      titleAr: 'مسند الشاميين',
      titleEn: 'Musnad al-Shamiyyin',
      authorAr: 'الإمام أبو القاسم الطبراني',
      authorEn: 'Imam Sulayman ibn Ahmad at-Tabarani',
      deathYear: '360 هـ',
      category: 'Canonical Collections & Musnads',
      categoryAr: 'أمهات كتب الحديث والمسانيد',
      description: 'Specialized collection documenting transmissions through the scholars of greater Syria.',
    ),
    BibliographyItem(
      id: 20,
      titleAr: 'مسند البزار (البحر الزخار)',
      titleEn: 'Musnad al-Bazzar',
      authorAr: 'الحافظ أبو بكر أحمد بن عمرو البزار',
      authorEn: 'Imam Abu Bakr Ahmad ibn Amr al-Bazzar',
      deathYear: '292 هـ',
      category: 'Canonical Collections & Musnads',
      categoryAr: 'أمهات كتب الحديث والمسانيد',
      description: 'Celebrated for in-depth chain analysis, narrator evaluations, and transmission identification.',
    ),

    // II. Hadith Compendiums & Legal Selections (جوامع السنة وأحاديث الأحكام)
    BibliographyItem(
      id: 21,
      titleAr: 'رياض الصالحين من كلام سيد المرسلين',
      titleEn: 'Riyadh as-Salihin',
      authorAr: 'الإمام محيي الدين يحيى بن شرف النووي',
      authorEn: 'Imam Yahya ibn Sharaf an-Nawawi',
      deathYear: '676 هـ',
      category: 'Compendiums & Legal Selections',
      categoryAr: 'جوامع السنة وأحاديث الأحكام',
      description: 'The universally acclaimed treasury of practical daily Sunnah and character development.',
    ),
    BibliographyItem(
      id: 22,
      titleAr: 'بلوغ المرام من أدلة الأحكام',
      titleEn: 'Bulugh al-Maram',
      authorAr: 'الحافظ شهاب الدين ابن حجر العسقلاني',
      authorEn: 'Hafiz Ibn Hajar al-Asqalani',
      deathYear: '852 هـ',
      category: 'Compendiums & Legal Selections',
      categoryAr: 'جوامع السنة وأحاديث الأحكام',
      description: 'Master legal compendium synthesizing primary textual proofs for Islamic jurisprudence.',
    ),
    BibliographyItem(
      id: 23,
      titleAr: 'عمدة الأحكام من كلام خير الأنام',
      titleEn: 'Umdat al-Ahkam',
      authorAr: 'الإمام عبد الغني بن عبد الواحد المقدسي',
      authorEn: 'Imam Abd al-Ghani al-Maqdisi',
      deathYear: '600 هـ',
      category: 'Compendiums & Legal Selections',
      categoryAr: 'جوامع السنة وأحاديث الأحكام',
      description: 'Concise collection restricted to mutually agreed upon (*Muttafaqun \'Alayh*) legal hadiths.',
    ),
    BibliographyItem(
      id: 24,
      titleAr: 'مشكاة المصابيح',
      titleEn: 'Mishkat al-Masabih',
      authorAr: 'الإمام محمد بن عبد الله الخطيب التبريزي',
      authorEn: 'Imam al-Khatib at-Tabrizi',
      deathYear: '741 هـ',
      category: 'Compendiums & Legal Selections',
      categoryAr: 'جوامع السنة وأحاديث الأحكام',
      description: 'The premier pedagogical compendium classifying traditions by canonical authority tiers.',
    ),
    BibliographyItem(
      id: 25,
      titleAr: 'شرح السنة',
      titleEn: 'Sharh as-Sunnah',
      authorAr: 'الإمام الحسين بن مسعود الفراء البغوي',
      authorEn: 'Imam al-Husayn ibn Mas\'ud al-Baghawi',
      deathYear: '516 هـ',
      category: 'Compendiums & Legal Selections',
      categoryAr: 'جوامع السنة وأحاديث الأحكام',
      description: 'Harmonizes theological principles with verified prophetic narrations and legal rulings.',
    ),
    BibliographyItem(
      id: 26,
      titleAr: 'الجامع الصغير وزيادته',
      titleEn: 'Al-Jami\' as-Saghir',
      authorAr: 'الإمام جلال الدين السيوطي',
      authorEn: 'Imam Jalal al-Din as-Suyuti',
      deathYear: '911 هـ',
      category: 'Compendiums & Legal Selections',
      categoryAr: 'جوامع السنة وأحاديث الأحكام',
      description: 'Alphabetical encyclopedia gathering short prophetic maxims and concise sayings.',
    ),
    BibliographyItem(
      id: 27,
      titleAr: 'مجمع الزوائد ومنبع الفوائد',
      titleEn: 'Majma\' az-Zawa\'id',
      authorAr: 'الحافظ نور الدين علي بن أبي بكر الهيثمي',
      authorEn: 'Hafiz Nur al-Din al-Haythami',
      deathYear: '807 هـ',
      category: 'Compendiums & Legal Selections',
      categoryAr: 'جوامع السنة وأحاديث الأحكام',
      description: 'Consolidated index of narrations in Ahmad, Abu Ya\'la, Bazzar, and Tabarani with narrator rulings.',
    ),
    BibliographyItem(
      id: 28,
      titleAr: 'الأربعون النووية',
      titleEn: 'Al-Arba\'un an-Nawawiyyah (40 Hadith)',
      authorAr: 'الإمام يحيى بن شرف النووي',
      authorEn: 'Imam Yahya ibn Sharaf an-Nawawi',
      deathYear: '676 هـ',
      category: 'Compendiums & Legal Selections',
      categoryAr: 'جوامع السنة وأحاديث الأحكام',
      description: 'The 42 core foundations of Islamic belief, worship, transaction, and character.',
    ),
    BibliographyItem(
      id: 29,
      titleAr: 'جامع العلوم والحكم في شرح خمسين حديثا من جوامع الكلم',
      titleEn: 'Jami\' al-Ulum wal-Hikam',
      authorAr: 'الإمام زين الدين عبد الرحمن بن رجب الحنبلي',
      authorEn: 'Imam Ibn Rajab al-Hanbali',
      deathYear: '795 هـ',
      category: 'Compendiums & Legal Selections',
      categoryAr: 'جوامع السنة وأحاديث الأحكام',
      description: 'Incomparable spiritual and juristic commentary explaining comprehensive Prophetic maxims.',
    ),

    // III. Canonical Classical Commentaries & Takhrij (شروح كتب السنة والتخريج)
    BibliographyItem(
      id: 30,
      titleAr: 'فتح الباري بشرح صحيح البخاري',
      titleEn: 'Fath al-Bari Sharh Sahih al-Bukhari',
      authorAr: 'الحافظ أحمد بن علي بن حجر العسقلاني',
      authorEn: 'Hafiz Ibn Hajar al-Asqalani',
      deathYear: '852 هـ',
      category: 'Classical Commentaries & Takhrij',
      categoryAr: 'شروح كتب السنة والتخريج',
      description: 'The undisputed master commentary on Sahih al-Bukhari; the crown jewel of Hadith scholarship.',
    ),
    BibliographyItem(
      id: 31,
      titleAr: 'المنهاج شرح صحيح مسلم بن الحجاج',
      titleEn: 'Al-Minhaj Sharh Sahih Muslim',
      authorAr: 'الإمام محيي الدين يحيى بن شرف النووي',
      authorEn: 'Imam Yahya ibn Sharaf an-Nawawi',
      deathYear: '676 هـ',
      category: 'Classical Commentaries & Takhrij',
      categoryAr: 'شروح كتب السنة والتخريج',
      description: 'Authoritative commentary detailing creed, juristic deductions, and linguistic terms in Sahih Muslim.',
    ),
    BibliographyItem(
      id: 32,
      titleAr: 'عون المعبود شرح سنن أبي داود',
      titleEn: '\'Awn al-Ma\'bud Sharh Sunan Abi Dawud',
      authorAr: 'العلامة محمد شمس الحق العظيم آبادي',
      authorEn: 'Allamah Muhammad Shams al-Haqq al-Azimabadi',
      deathYear: '1329 هـ',
      category: 'Classical Commentaries & Takhrij',
      categoryAr: 'شروح كتب السنة والتخريج',
      description: 'Lucid and meticulous commentary clarifying legal deductions and narrator positions in Sunan Abi Dawud.',
    ),
    BibliographyItem(
      id: 33,
      titleAr: 'تحفة الأحوذي بشرح جامع الترمذي',
      titleEn: 'Tuhfat al-Ahwadhi Sharh Jami\' at-Tirmidhi',
      authorAr: 'العلامة محمد عبد الرحمن المباركفوري',
      authorEn: 'Allamah Muhammad Abd al-Rahman al-Mubarakpuri',
      deathYear: '1353 هـ',
      category: 'Classical Commentaries & Takhrij',
      categoryAr: 'شروح كتب السنة والتخريج',
      description: 'Deep analytical explanation elucidating hadith rulings and madhhab reconciliations in at-Tirmidhi.',
    ),
    BibliographyItem(
      id: 34,
      titleAr: 'حاشية السندي على سنن النسائي',
      titleEn: 'Hashiyat as-Sindi \'ala Sunan an-Nasa\'i',
      authorAr: 'العلامة محمد بن عبد الهادي السندي',
      authorEn: 'Allamah Muhammad ibn Abd al-Hadi as-Sindi',
      deathYear: '1138 هـ',
      category: 'Classical Commentaries & Takhrij',
      categoryAr: 'شروح كتب السنة والتخريج',
      description: 'Precise marginal commentary resolving linguistic, syntactical, and legal points in an-Nasa\'i.',
    ),
    BibliographyItem(
      id: 35,
      titleAr: 'حاشية السندي على سنن ابن ماجه',
      titleEn: 'Hashiyat as-Sindi \'ala Sunan Ibn Majah',
      authorAr: 'العلامة محمد بن عبد الهادي السندي',
      authorEn: 'Allamah Muhammad ibn Abd al-Hadi as-Sindi',
      deathYear: '1138 هـ',
      category: 'Classical Commentaries & Takhrij',
      categoryAr: 'شروح كتب السنة والتخريج',
      description: 'Standard scholarly gloss illuminating chapter headings and narrations in Sunan Ibn Majah.',
    ),
    BibliographyItem(
      id: 36,
      titleAr: 'سبل السلام الموصلة إلى بلوغ المرام',
      titleEn: 'Subul as-Salam Sharh Bulugh al-Maram',
      authorAr: 'الإمام محمد بن إسماعيل الصنعاني',
      authorEn: 'Imam Muhammad ibn Isma\'il as-San\'ani',
      deathYear: '1182 هـ',
      category: 'Classical Commentaries & Takhrij',
      categoryAr: 'شروح كتب السنة والتخريج',
      description: 'In-depth legal commentary extracting rulings and authentic opinions directly from evidence.',
    ),
    BibliographyItem(
      id: 37,
      titleAr: 'نيل الأوطار من أسرار منتقى الأخبار',
      titleEn: 'Nayl al-Awtar',
      authorAr: 'الإمام محمد بن علي الشوكاني',
      authorEn: 'Imam Muhammad ibn Ali ash-Shawkani',
      deathYear: '1250 هـ',
      category: 'Classical Commentaries & Takhrij',
      categoryAr: 'شروح كتب السنة والتخريج',
      description: 'Masterwork of comparative jurisprudence assessing authentic hadith chains and juristic inferences.',
    ),
    BibliographyItem(
      id: 38,
      titleAr: 'مرقاة المفاتيح شرح مشكاة المصابيح',
      titleEn: 'Mirqat al-Mafatih Sharh Mishkat al-Masabih',
      authorAr: 'العلامة علي بن سلطان محمد القاري الهروي',
      authorEn: 'Allamah Mulla Ali al-Qari',
      deathYear: '1014 هـ',
      category: 'Classical Commentaries & Takhrij',
      categoryAr: 'شروح كتب السنة والتخريج',
      description: 'Vast encyclopedia of hadith meanings, doctrinal tenets, linguistic nuances, and legal rulings.',
    ),
    BibliographyItem(
      id: 39,
      titleAr: 'سلسلة الأحاديث الصحيحة وشيء من فقهها وفوائدها',
      titleEn: 'Silsilat al-Ahadith as-Sahihah',
      authorAr: 'المحدث محمد ناصر الدين الألباني',
      authorEn: 'Shaykh Muhammad Nasir al-Din al-Albani',
      deathYear: '1420 هـ',
      category: 'Classical Commentaries & Takhrij',
      categoryAr: 'شروح كتب السنة والتخريج',
      description: 'Contemporary master verification assembling sound narrations and extracting lessons and fiqh.',
    ),
  ];
}
